version: '3'
services:

  # REST interface for POST and GET of sentiments
  mean-sentiment-datastore:
    build: ./mean-sentiment-datastore
    expose:
      - "5000"
    volumes:
      - "/var/lib/sentiment/db:/var/lib/db"
    environment:
      - DEFAULT_FROM=one month ago
    restart: always

  top-tweets-datastore:
    build: ./top-tweets-datastore
    expose:
      - "5000"
    volumes:
      - "/var/lib/sentiment/db:/var/lib/db"
    environment:
      - DEFAULT_FROM=one month ago
    restart: always

  worst-tweets-datastore:
    build: ./worst-tweets-datastore
    expose:
      - "5000"
    volumes:
      - "/var/lib/sentiment/db:/var/lib/db"
    environment:
      - DEFAULT_FROM=one month ago
    restart: always
    
  react:
    image: node
    volumes:
      - "./ui:/usr/src/app"
    environment:
      - NODE_ENV=debug
    expose:
      - "3000"
    restart: always
    working_dir: /usr/src/app
    entrypoint: /usr/src/app/run
    depends_on:
      - mean-sentiment-datastore
    
  # Proxies the REST service, blocks POST requests from
  # the "outside"
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - mean-sentiment-datastore
      - top-tweets-datastore
      - react
    restart: always

  # Analyzer, pulls stream from twitter - analyzes - and
  # posts aggregated data to mean-sentiment-datastore
  analyzer-trump:
    build: ./analyzer
    depends_on:
      - mean-sentiment-datastore
      - top-tweets-datastore
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - MODEL
      - VOCAB
      - MEAN_SENTIMENT_DATASTORE=mean-sentiment-datastore:5000
      - TOP_TWEETS_DATASTORE=top-tweets-datastore:5000
      - WORST_TWEETS_DATASTORE=worst-tweets-datastore:5000
      - KEY=trump
      - PERIOD=1 minute
    command: "@realDonaldTrump"
    restart: always

  analyzer-hillary:
    build: ./analyzer
    depends_on:
      - mean-sentiment-datastore
      - top-tweets-datastore
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - MODEL
      - VOCAB
      - MEAN_SENTIMENT_DATASTORE=mean-sentiment-datastore:5000
      - TOP_TWEETS_DATASTORE=top-tweets-datastore:5000
      - WORST_TWEETS_DATASTORE=worst-tweets-datastore:5000
      - KEY=hillary
      - PERIOD=1 minute
    command: "@HillaryClinton"
    restart: always
    
