version: '3'
services:

  datastore:
    build: ./datastore
    expose:
      - "5000"
    restart: always

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - datastore
    restart: always
    
  analyzer-trump:
    build: ./analyzer
    depends_on:
      - datastore
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - MODEL
      - VOCAB
      - DATASTORE=datastore:5000
      - KEY=trump
      - PERIOD=10 seconds
    command: "@realDonaldTrump"
    restart: always
