version: '3'
services:

  # REST interface for POST and GET of sentiments
  datastore:
    build: ./datastore
    expose:
      - "5000"
    volumes:
      - "/var/lib/sentiment/db:/var/lib/db"
    environment:
      - DEFAULT_FROM=one month ago
    restart: always

  react:
    image: node
    volumes:
      - "./ui:/usr/src/app"
    environment:
      - NODE_ENV=debug
    ports:
      - "3000:3000"
    restart: always
    working_dir: /usr/src/app
    entrypoint: /usr/src/app/run
    
  # Proxies the REST service, blocks POST requests from
  # the "outside"
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - datastore
    restart: always

  # Analyzer, pulls stream from twitter - analyzes - and
  # posts aggregated data to datastore
  analyzer-trump:
    build: ./analyzer
    depends_on:
      - datastore
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - MODEL
      - VOCAB
      - DATASTORE=datastore:5000
      - KEY=trump
      - PERIOD=1 minute
    command: "@realDonaldTrump"
    restart: always
