version: '3'
services:

  # The influxdb stores time series data
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - "/var/lib/sentiment/influxdb:/var/lib/influxdb"

  kapacitor:
    image: kapacitor
    depends_on:
      - influxdb
    ports:
      - "9092:9092"
    volumes:
      - "./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro"
      - "./tick:/usr/share/tick:ro"
      - "/var/lib/sentiment/kapacitor:/var/lib/kapacitor"

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - "3001:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.10.236/grafana
      - GF_SECURITY_ADMIN_PASSWORD=321ytrewq
    volumes:
      - "/var/lib/sentiment/grafana:/var/lib/grafana"
      
  # REST interface for POST and GET of sentiments
  mean-sentiment-datastore:
    build: ./mean-sentiment-datastore
    depends_on:
      - influxdb    
    expose:
      - "5000"
    volumes:
      - "/var/lib/sentiment/db:/var/lib/db"
    environment:
      - DEFAULT_RESOLUTION=hour
    restart: always
    
  react:
    image: node
    volumes:
      - "./ui:/usr/src/app"
    environment:
      - NODE_ENV=debug
    expose:
      - "3000"
    restart: always
    working_dir: /usr/src/app
    entrypoint: /usr/src/app/run
    depends_on:
      - mean-sentiment-datastore
    
  # Proxies the REST service, blocks POST requests from
  # the "outside"
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - mean-sentiment-datastore
      - react
    restart: always

  # Analyzer, pulls stream from twitter - analyzes - and
  # posts aggregated data to mean-sentiment-datastore
  analyzer:
    build: ./analyzer
    depends_on:
      - influxdb
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - MODEL
      - VOCAB
    command: "@realDonaldTrump @HillaryClinton @BarackObama @mike_pence @SenJohnMcCain @SpeakerRyan @MittRomney @IvankaTrump @tedcruz"
    restart: always
